// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213234624_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Description = "Paracetamol 500mg for pain relief and fever.",
                            Name = "Panadol Advance"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            Description = "Amoxicillin 500mg Broad-spectrum antibiotic.",
                            Name = "Amoxil"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f"),
                            Description = "Diclofenac Sodium 50mg Non-steroidal anti-inflammatory drug (NSAID).",
                            Name = "Voltaren"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d8e-1f2a-3b4c5d6e7f8a"),
                            Description = "Furosemide 40mg Diuretic for fluid retention.",
                            Name = "Lasix"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e9f-2a3b-4c5d6e7f8a9b"),
                            Description = "Co-amoxiclav 1g Antibiotic for bacterial infections.",
                            Name = "Augmentin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Pharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pharmacies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-1111-2222-3333-444444444444"),
                            Address = "Baghdad, Palestine St",
                            Name = "Al-Amal Pharmacy",
                            PhoneNumber = "+9647811122233",
                            UserId = new Guid("f4d5e6f7-a8b9-4d8e-1f2a-3b4c5d6e7f8a")
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-2222-3333-444444444444"),
                            Address = "Erbil, 60 Meter Rd",
                            Name = "Zheen Pharmacy",
                            PhoneNumber = "+9647501112223",
                            UserId = new Guid("f5e6f7a8-b9c0-4e9f-2a3b-4c5d6e7f8a9b")
                        },
                        new
                        {
                            Id = new Guid("99999999-1111-2222-3333-444444444444"),
                            Address = "Basra, Corniche",
                            Name = "Al-Fayhaa Pharmacy",
                            PhoneNumber = "+9647711122233",
                            UserId = new Guid("f6f7a8b9-c0d1-4f0a-3b4c-5d6e7f8a9b0c")
                        });
                });

            modelBuilder.Entity("Domain.Entities.PharmacyMedicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyMedicines");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServicesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            Address = "Baghdad, Al-Mansour District",
                            Name = "Iraqi Pharmaceutical Industry",
                            PhoneNumber = "+9647801234567",
                            ServicesDescription = "Local manufacturer and wholesale distributor.",
                            UserId = new Guid("f1a2b3c4-d5e6-4a5b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            Address = "Erbil, Industrial Zone",
                            Name = "Pioneer Pharmaceutical Industries",
                            PhoneNumber = "+9647501234567",
                            ServicesDescription = "Import/Export and large scale distribution.",
                            UserId = new Guid("f2b3c4d5-e6f7-4b6c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            Address = "Baghdad, Baghdad Al-Jadida",
                            Name = "Al-Mansour Pharmaceuticals",
                            PhoneNumber = "+9647701234567",
                            ServicesDescription = "Specialized in chronic disease medications.",
                            UserId = new Guid("f3c4d5e6-f7a8-4c7d-0e1f-2a3b4c5d6e7f")
                        });
                });

            modelBuilder.Entity("Domain.Entities.SupplierMedicine", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("WholesalePrice")
                        .HasColumnType("numeric");

                    b.HasKey("SupplierId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("SupplierMedicines");

                    b.HasData(
                        new
                        {
                            SupplierId = new Guid("11111111-2222-3333-4444-555555555555"),
                            MedicineId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            MinimumOrderQuantity = 10,
                            StockQuantity = 500,
                            WholesalePrice = 1250m
                        },
                        new
                        {
                            SupplierId = new Guid("11111111-2222-3333-4444-555555555555"),
                            MedicineId = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            MinimumOrderQuantity = 5,
                            StockQuantity = 200,
                            WholesalePrice = 3500m
                        },
                        new
                        {
                            SupplierId = new Guid("11111111-2222-3333-4444-555555555555"),
                            MedicineId = new Guid("e5f6a7b8-c9d0-4e9f-2a3b-4c5d6e7f8a9b"),
                            MinimumOrderQuantity = 3,
                            StockQuantity = 100,
                            WholesalePrice = 8000m
                        },
                        new
                        {
                            SupplierId = new Guid("22222222-3333-4444-5555-666666666666"),
                            MedicineId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            MinimumOrderQuantity = 20,
                            StockQuantity = 1000,
                            WholesalePrice = 1200m
                        },
                        new
                        {
                            SupplierId = new Guid("22222222-3333-4444-5555-666666666666"),
                            MedicineId = new Guid("c3d4e5f6-a7b8-4c7d-0e1f-2a3b4c5d6e7f"),
                            MinimumOrderQuantity = 10,
                            StockQuantity = 350,
                            WholesalePrice = 2500m
                        },
                        new
                        {
                            SupplierId = new Guid("33333333-4444-5555-6666-777777777777"),
                            MedicineId = new Guid("b2c3d4e5-f6a7-4b6c-9d0e-1f2a3b4c5d6e"),
                            MinimumOrderQuantity = 5,
                            StockQuantity = 150,
                            WholesalePrice = 3600m
                        },
                        new
                        {
                            SupplierId = new Guid("33333333-4444-5555-6666-777777777777"),
                            MedicineId = new Guid("d4e5f6a7-b8c9-4d8e-1f2a-3b4c5d6e7f8a"),
                            MinimumOrderQuantity = 10,
                            StockQuantity = 400,
                            WholesalePrice = 1500m
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Email = "admin@iqpharma.com",
                            Name = "Iraqi Pharma Admin",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f2b3c4d5-e6f7-4b6c-9d0e-1f2a3b4c5d6e"),
                            Email = "admin@pioneer.iq",
                            Name = "Pioneer Admin",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f3c4d5e6-f7a8-4c7d-0e1f-2a3b4c5d6e7f"),
                            Email = "admin@mansour.com",
                            Name = "Mansour Pharma Admin",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f4d5e6f7-a8b9-4d8e-1f2a-3b4c5d6e7f8a"),
                            Email = "owner@baghdadpharma.com",
                            Name = "Baghdad Pharmacy Owner",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("f5e6f7a8-b9c0-4e9f-2a3b-4c5d6e7f8a9b"),
                            Email = "owner@erbilpharma.com",
                            Name = "Erbil Pharmacy Owner",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("f6f7a8b9-c0d1-4f0a-3b4c-5d6e7f8a9b0c"),
                            Email = "owner@basrapharma.com",
                            Name = "Basra Pharmacy Owner",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Pharmacy", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Pharmacy")
                        .HasForeignKey("Domain.Entities.Pharmacy", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PharmacyMedicine", b =>
                {
                    b.HasOne("Domain.Entities.Medicine", "Medicine")
                        .WithMany("PharmacyMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyMedicines")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Supplier")
                        .HasForeignKey("Domain.Entities.Supplier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SupplierMedicine", b =>
                {
                    b.HasOne("Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany("SupplierMedicines")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.Medicine", b =>
                {
                    b.Navigation("PharmacyMedicines");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Pharmacy", b =>
                {
                    b.Navigation("PharmacyMedicines");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierMedicines");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Pharmacy");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
